### ISSUE TITLE
UTF8 characters in generated CSV metadata render incorrectly in Excel

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#148]
There's two classes of problems here: (1) UTF8 chars for place names (not sure what to do about this) and (2) characters we use in the metadata (usually dashes or the º symbol).  Excel for Mac (V16) doesn't handle these and displays garbage.

For (2) here's an example:
<img width="591" alt="Screen Shot 2022-03-22 at 7 06 03 PM" src="https://user-images.githubusercontent.com/525049/159609035-52750e4a-e1e0-42ce-b4e4-9d56ea41937e.png">

The dash characters are just UTF8 chars for the last two (copy/paste thing) and easy to correct.  For the data sources, though, it could be a touch more nuanced because (C) looks a bit like "Copyright" ... so maybe (deg C) or something.  Or perhaps it's just "this is an Excel issue, won't fix."

This works fine in Numbers and LibreOffice.

**Comment by brucecrevensten** [comment]
This could be a piece of a "fix" -- https://pydash.readthedocs.io/en/latest/api.html#pydash.strings.deburr

**Comment by cstephen** [comment]
I did some digging and apparently the reason Excel does not understand UTF-8 characters in our CSV files by default is because Excel expects to see a byte order mark (BOM) at the beginning of the CSV file, which is a non-standard requirement. From Wikipedia:

> The Unicode Standard permits the BOM in UTF-8 but does not require or recommend its use. Byte order has no meaning in UTF-8, so its only use in UTF-8 is to signal at the start that the text stream is encoded in UTF-8, or that it was converted to UTF-8 from a stream that contained an optional BOM.

From: https://en.wikipedia.org/wiki/Byte_order_mark

If, instead of opening a CSV file directly in Excel, you create a blank sheet and import the CSV file, it allows you to choose the character encoding and fixes this issue without modifying the CSV file

It is possible to add a BOM byte sequence to a CSV file's content (see: https://stackoverflow.com/questions/5202648/adding-bom-unicode-signature-while-saving-file-in-python), but it doesn't sound like a normal/common thing to do, and I'm afraid it could impact non-Excel spreadsheet applications and scripts. So, I'm in favor of simply changing the `°C` to `deg C` as suggested in this ticket. Seems like the most foolproof solution.
