### ISSUE TITLE
Fix issues with polygon mask array shape not matching data array shape

### ISSUE THREAD

**Issue by cstephen** [ua-snap/data-api#162]
This affects any endpoint that averages data over an area (including flammability, vegetation type, temperature, precipitation). If you load any area query, more often than not the polygon mask array for area will have a slightly difference shape vs. the original data. The shape mismatch causes server errors when this line of code is called:

```
data_arr_mask = np.broadcast_to(poly_mask_arr.mask, data_arr.shape)
```

If you commented out the try/except block wrapped around the line above, errors like this will show up in the console output:

```
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (128,188)  and requested shape (140,127,187)
```

Our current workaround for this is to crop the polygon mask array to fork it into the correct shape. Can we solve this by adding a bit of buffer/padding around the polygon bounding box when the data is requested from Rasdaman?

**Comment by charparr** [comment]
After tussling with this for a bit I think your fix of forcing the polygon mask array to the correct shape
`cropped_poly_mask = poly_mask_arr[0:xy_shape[1], 0:xy_shape[0]]`

is a better approach, at least for now, compared to buffering or padding the bounding box values that are sent to Rasdaman. Here's why - we'd need to provide Rasdaman the "Goldilocks" bounding box to get the requested shape values to match those of `poly_mask_arr`.

If the padding / buffering is too small, it won't include any extra grid cells!
If the padding / buggering is too large, it will include too many extra grid cells! And then we have this same `broadcast_to` error, just reversed.

Even if we "cheat" and know the size (spatial resolution) of the data coming in from Rasdaman, figuring out how far we have to move in geography-land (the request string) to get what we want in gridded-land will be tricky because we'd need to know cell edges, centers, distances, etc. and the rules for how those get parsed.
