### ISSUE TITLE
Check for HTTP code - template mismatch?

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#213]
https://github.com/ua-snap/data-api/blob/24467ccfdb2d5b70e804b8ecec0c4fa6abe69183/validate_request.py#L78

**Comment by BobTorgerson** [comment]
Since the update to using Geoserver, we have updated the validate_var_id function and I believe that the invalid_area template is the correct one to use in this function. It is explicitly used to determine if a provided area ID is valid by searching through all areas and the HUC 12s if the normal areas do not contain the area ID.
