### ISSUE TITLE
Bounds issue when gathering data for processing by area (HUC)

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#22]
http://localhost:5000/iem/huc/19010107

Tracing the error back, Rasdaman's saying this: `subsetting '1461594.265783991:1550326.0946727118' is not within coverage's geo bounds '-2173225.118142955:1498276.881857045' for axis 'X'.`

**Comment by charparr** [comment]
I think we can close this? See http://snap-data.io/taspr/huc/19010107
The results look good to me.

`iem` is no longer a top-level route and was replaced by `taspr`

The HUC response looks good too:
http://snap-data.io/huc/huc8/19010107

**Comment by kyleredilla** [comment]
Hmm, that is kind of interesting. I'm not sure what would have caused that specific error, unless it was an early coverage without the full IEM extent or something, because the current X domain is [-2169223.206087799, 1820776.793912201]. I could see how this particular HUC could trigger that error if the coverage were only the extent of AK. But yeah I guess I would agree, this doesn't look like an issue anymore. 

![image](https://user-images.githubusercontent.com/29390510/149576532-081bfe34-0e80-4a30-8d19-5675ae5e5335.png)

**Comment by charparr** [comment]
That seems good to me Kyle! The API + rasdaman ingests were pretty immature when this error came up initially. Closing.
