### ISSUE TITLE
Truncate historical ERA-Interim data request to match re-processed coverages

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#227]
Pending completion of [this rasdman-ingest ticket](https://github.com/ua-snap/rasdaman-ingest/issues/51):

The historical period should change to 1980 to 2010, or 1980-2009.
The below line will probably need to change, and whatever similar lines exist in this route, and in the design index endpoints too.

https://github.com/ua-snap/data-api/blob/87d779db10bde105e7f8645a2ed446099b5c35e6/routes/degree_days.py#L52

**Comment by charparr** [comment]
Hey I think we can close this ticket! We are ditching `horp` so that basically eliminates the API side of this issue, and the linked rasdaman-ingest ticket is tracking this and once we migrate our degree day coverages to Zeus the API + backend will be in sync.

**Comment by cstephen** [comment]
Even after removing the historical/projected/horp options, users are still able to provide a custom year range to Degree Days endpoints (since it's still applicable for `?summarize=mmm` style summaries), so we still need min/max years defined in the endpoint script for input validation. However! It looks like the change to the year range already made it into the `main` branch somewhere along the way:

https://github.com/ua-snap/data-api/blob/e785c40d3c3b9f25b05f75a2c21cba08633872b3/routes/degree_days.py#L42

So, I think this ticket can be closed regardless.
