### ISSUE TITLE
Look into using avg function in WCPS

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/data-api#238]
Well it looks like we have already [used the `avg` function](https://github.com/ua-snap/data-api/blob/e71552fe82a811108ab291e57255954b5ca8c0d2/routes/taspr.py#L267), and so presumably have good reason in cases where it is not used and things are summed and divided, like in [this snippet](https://github.com/ua-snap/data-api/blob/e71552fe82a811108ab291e57255954b5ca8c0d2/generate_requests.py#L149):

```
        f"ProcessCoverages&query=for $c in ({cov_id}) "
        f"let $a := (condense + over $t {summary_str} "
        f"using $c[{axis_name}($t),X({x}),Y({y}){subset_str}] ) / {n} "
        f'return encode( $a , "application/{encoding}")'
```

... but just make sure that this is the case. Look for other instances of this as well. 
This is a general ticket to aid in "cleaning" the API for a V1.

**Comment by cstephen** [comment]
I spent a couple hours looking at this and I'm convinced that we are already using the `avg` function everywhere it is practical to do so. Here are some notes on what I found:

If you take this WCPS query for example:

```
for $c in (iem_ar5_2km_taspr_seasonal)
let $a := (condense + over $t decade(6:8)
using $c[decade($t),X(368046.86664054624),Y(1699798.1555357035),varname(1)] ) / 3
return encode($a , "application/json")
```

This will return hierarchical results of a separate condense operation for each combination of axes that was not specified in the `using` clause. In other words, since `decade`, `X`, `Y`, and `varname` are specified in the `using` clause above, a condense operation will be performed for each combination of the remaining axes (`season` x `model` x `scenario`), returning this:

```
[ # season
  [ # model
    [-15.09999974568685, -14.26666673024496, -12.10000006357829], # scenario
    [-14.66666666666667, -14.03333346048991, -10.70000012715658], # scenario
    [-15.83333301544189, -15.93333371480306, -14.40000025431315] # scenario
  ],
  [
    [15.16666666666667, 15.66666666666667, 16.89999961853027],
    [15.79999987284342, 16.46666717529297, 17.53333346048991],
    [13.53333314259847, 13.83333301544189, 14.53333346048991]
  ],
  [
    [0.366666667163372, 1.266666690508525, 2.433333317438761],
    [1.100000003973643, 1.699999968210856, 3.633333325386047],
    [-1.23333332935969, -0.4000000084439914, 0.2000000029802322]
  ],
  [
    [-2.199999968210856, -2.166666666666667, 0.0333333338300387],
    [-2.100000023841858, -1.433333357175191, 0.5666666577259699],
    [-2.699999968210856, -2.600000063578288, -1.066666662693024]
  ]
]
```

Looking at the Rasdaman cheatsheets here:
https://doc.rasdaman.org/11_cheatsheets.html

The `over` and `using` clauses are exclusively used for the `condense` aggregation type, and only the `+`, `*`, `max`, `min`, `and`, and `or` operators are compatible with the `condense` aggregation type. So, we cannot use `avg` with `condense`, and we cannot use the `over` and `using` clauses since those only work with `condense`. 

This is the closest I got to rewriting the original WCPS query using `avg`, given the limitations mentioned above:

```
for $c in (iem_ar5_2km_taspr_seasonal)
let $a := avg($c[decade(6:8),X(368046.86664054624),Y(1699798.1555357035),varname(1)])
return encode($a , "application/json")
```

This runs, but instead of returning the hierarchical output above, it returns a single scaler that is the single average across all specified axes and values:

```
0.2166666449909961
```

So, `avg` is a great fit for our min/mean/max (`mmm`) endpoints where each WCPS query produces a single value, but for all other endpoints it seems not to be a great fit.
