### ISSUE TITLE
Are dataset source references referenced from a consistent "level" in the API?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#259]
It's important to have links to source data.  Sometimes this documentation is happening at the "dataset/var" level (ALFRESCO), sometimes it's at the "subset type" level (point, polygon).  Can we be more consistent, or is this OK?

**Comment by cstephen** [comment]
Closed in #290.

This has become a non-issue since all of the documentation has been "flattened" into 2nd-level "service category" pages. There are no longer separate pages for datasets, point queries, area queries, etc., so all documentation, including source data and academic reference links, is now consistently displayed in 2nd-level pages.
