### ISSUE TITLE
Warning displayed with `veg_type` endpoint, is this a concern?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#272]
route: /alfresco/veg_type/area/USFS3

warning:
```
.../data-api/routes/alfresco.py:266: RuntimeWarning: Mean of empty slice
  results = np.nanmean(data_arr, axis=(1, 2)).astype(float)
```

Is this a concern?  Also ref #175, #176

**Comment by BobTorgerson** [comment]
Ref: https://github.com/ua-snap/data-api/issues/458

**Comment by Joshdpaul** [comment]
This warning is expected behavior when trying to compute the `np.nanmean()` of an array which is all NaNs. The ALFRESCO vegetation area percentage will include NaNs if some veg types are missing from the AOI.

For example, this `/alfresco/veg_type/area/USFS3` route is in SE Alaska and only returns values for veg types "temperate rainforest" or "not modeled" - the rest of the veg types are 100% NaN, and so taking a mean across each veg type must be computing some entirely NaN arrays.
