### ISSUE TITLE
Fix unit character in generated CSV for degree days (possibly others)

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#342]
Excel / MacOS.

Use http://localhost:5000/degree_days/heating/65.0628/-146.1627?format=csv

Observe `dd is the total annual degree days below 65¬∞F for the specified model` in the generated CSV.

**Comment by cstephen** [comment]
We have decided to replace "special" (UTF-8) characters in our CSV metadata with their non-special equivalent. For degrees, for example, instead of writing `°F`, we have come up with a de facto convention of writing `(deg F)`. 

Unfortunately, there's no straightforward fix for the Indigenous names that sometimes (though rarely) have special UTF-8 characters of their own. Last time I looked into this (months ago), and I think it still applies now, I discovered that Excel does not detect UTF-8 content in CSV files unless:

- The user manually imports the CSV file and specifies UTF-8 during the process
- The CSV file itself begins with the UTF-8 "byte order mark" to communicate to Excel that it should be read in UTF-8 mode.

Unfortunately, according to Wikipedia:

> The Unicode Standard permits the BOM in UTF-8 but does not require or recommend its use.

> BOM use is optional. Its presence interferes with the use of UTF-8 by software that does not expect non-ASCII bytes at the start of a file but that could otherwise handle the text stream.

See the following for more info:

- https://en.wikipedia.org/wiki/Byte_order_mark
- https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

This seems more like an Excel problem than a problem with our CSVs, and I'm afraid of making the CSVs harder to work with in scripts, etc., to accommodate nonstandard Excel behavior.
