### ISSUE TITLE
Add elevation data (DEM) to API

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#40]
We want to be able to query elevation for points, as well as providing min/max/mean for areas.  To do this, we may be able to leverage existing APIs, or, we'd need to load a local DEM and query it directly.  Target resolution at 2km since that's going to align with a lot of our existing data; 771m may be another option, depending on regridding/etc.

**Comment by charparr** [comment]
I'm grabbing the [ASTER GDEMv3](https://lpdaac.usgs.gov/products/astgtmv003/) for this because it 
 - has high latitude coverage (up to 83 deg. N and S)
 - is recent
 - is transboundary
 - does not have holes (like the Arctic DEM)
 - has water body masking + filtering baked in
 - has a reasonable native resolution (1 arc second, i.e. ~30 m at equator) to downsample to 0.771 / 1.0 / 2.0 km.

I'm fetching a big swath of this (many tiles) on `atlas_scratch` right now.

**Comment by charparr** [comment]
1 km resolution:
![image](https://user-images.githubusercontent.com/7774271/150042393-052a3b9a-800d-43f5-8273-dbdd58994253.png)

**Comment by charparr** [comment]
Same 1 km result but I zoomed in and made it look cold.
<img width="1043" alt="akz" src="https://user-images.githubusercontent.com/7774271/150044856-26e2410a-cd11-4027-88e8-ea8a79a81aa5.png">

**Comment by charparr** [comment]
Negative values between -1 and -50 meters *are* valid for this DEM. See Ikpek Lagoon (Seward Peninsula). The bright red overlay is where ASTER GDEM v3 has negative values. This makes sense - these lagoons are here because seawater flows in at times - they're below sea level. Minimum value for this AKCAN extent is -7 m. 

![image](https://user-images.githubusercontent.com/7774271/150167504-75ea0c6d-d006-4ded-ba26-bfc8c2b791a2.png)

**Comment by charparr** [comment]
So rather than just return one elevation value per point query, I think the more sensible move is to return three: `zmin` , `zmax`, and `zavg`. This is because the current interpolation (GDAL default of nearest-neighbor) will not return true min or max values for a given square kilometer (current DEM spatial resolution). This means creating a three-band DEM where each band create using [interpolation flags](https://gdal.org/programs/gdalwarp.html) `min` `max` or `average`. This way, if a coastal area is queried, you'll get the elevation of `0` for the sea level, some elevation that is more representative of the community or coast, and then some bounding upper elevation. This will also will limit scenarios where a user chooses the summit of Denali and tells us the value is too low.
