### ISSUE TITLE
Allow CSV endpoints to accept a place name

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/data-api#47]
When apps request data in CSV format, the generated file should have a decent name.  Accept a `name` parameter, URL-encoded, which can be used to generate a filename.

**Comment by cstephen** [comment]
This was implemented slightly differently in branch `csvs_for_iem_webapp`. In this branch, the API is using the community ID, HUC ID, or protected area ID to derive the name of the community from the API's location JSON files. This functions as input validation and ensures that CSV filenames and the location name in the CSV metadata can only be named after our list of communities. However, since single point community data is requested using just lat/lon, an additional `community` GET parameter is added to single point community requests from the web app side.
