### ISSUE TITLE
Implement CSV return for all endpoints.

### ISSUE THREAD

**Issue by charparr** [ua-snap/data-api#50]
Consider making it the default, rather than JSON. This would avoid implementation in the web app.

**Comment by brucecrevensten** [comment]
We won't want this for _all_ endpoints (not ones that return min/mean/max, for example, because that's trivial) but for many endpoints which return deep data that could be useful in CSV format, we'd want to implement this.

All endpoints that implement CSV output should have that documented in their relevant page.  (I missed this on the Sea Ice %Conc branch recently).

**Comment by cstephen** [comment]
I took an inventory of the endpoints that do not support CSV output and it looks like we're in pretty good shape.

The output of these endpoints is too brief (summary level) for meaningful CSV output IMO:

- Elevation Point Query
- Geology Point Query
- Glaciology
- Mean Annual Precipitation
- Physiography
- Wildfire

Also, most of the "Physical and Administrative Boundary Polygons" endpoints return GeoJSON data, so CSV support is not applicable for those.

The one case I found where I think we should add CSV support is the `/places/all` endpoint. Several other endpoints link to the `/places/all` endpoint as the place where users can look up place IDs. But most users will just see an unformatted blob of JSON when they go here, so I think we should add CSV support to the `/places/all` endpoint and link to the CSV version of the URL in other parts of the documentation. I'll plan to implement this.
